os:
  - linux
#  - osx

language: go
go:
  - 1.13.x
env:
  - GO111MODULE=on

script:
  - go mod init .
  - go build -o x.bin .
  - ./x.bin

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: x.bin
  skip_cleanup: true
  on:
    tags: true
